### PR TITLE
need to recompile instead of copy

### PR DESCRIPTION
**Pull request by frodopwns**
updated dist directory not showing up in release, this fixes it

### CODE REVIEW

**Comment by frodopwns** [comment]
still testing this

**Comment by seushermsft** [comment]
This works on my machine, though I don't know why we have to build instead of copy.

**Comment by frodopwns** [comment]
It worked for me the first time but then I started getting weirdness, so I'm going to look at this a little longer

**Comment by frodopwns** [comment]
This one doesn't work right because `tscript` was moved to `devDependencies`, which is correct, so I will have to rework this

**Pull request closed without merging**
